---
title: "BlogdownBlog_13Mar2020"
author: "Kristan"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Steps for setting up website were found here: https://www.storybench.org/how-to-build-a-website-with-blogdown-in-r/

```{r, install packages}

#Install and load blogdown package
install.packages("blogdown")
library(blogdown)

blogdown::update_hugo #updates Hugo to latest version

```

```{r, build new website}

blogdown::new_site(theme = "yoshiharuyamashita/blackburn") #creates site using blackburn theme

#Running this code chunk will open up new windows, and create Hugo site

```
```{r, check if new site is working}
#first, update site in your config.toml file and save changes as listed in steps on website. to update website with changes, run "serve site"

blogdown::serve_site() #test if new site is working

#here you can either use use git status in terminal window to check what's going on with files in repository, or use the Git pane to add, commit, pull, or push changes within projects. see website for more details!

#Use Netlify (login to Github first) to set up domain, purchase my own unique domain, then configure DNS to drive traffic to my website

```

```{r, create new posts}
#to create new posts, go to the "content" folder in the site 

```

